fede_crud:
    resource: "@FedeCRUDBundle/Resources/config/routing.yml"
    prefix:   /CRUD

fede_twig:
    resource: "@FedeTwigBundle/Resources/config/routing.yml"
    prefix:   /FedeTwig

fede_racine:
    resource: "@FedeRacineBundle/Resources/config/routing.yml"
    prefix:   /


